//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public string MaSP { get; set; }
        public int MaSK { get; set; }
        public Nullable<int> SLToiThieu { get; set; }
        public Nullable<decimal> Giam { get; set; }
        public Nullable<bool> PhanTram { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual SuKien SuKien { get; set; }
    }
}
