//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public string HinhAnh { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string CMND { get; set; }
        public Nullable<decimal> Luong { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
