//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCau
    {
        public int MaYC { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> SLYeuCau { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
